/**
 * E2E: GURMINA.USD.2024.01 — payment schedule UI verification
 *
 * Seeds IndexedDB directly with the Gurmina instrument, purchase lot, and the
 * payment records that the fixed algorithm should produce, then verifies the UI.
 *
 * Reference: docs/examples/gurnima-algorithm.md
 * Amounts verified in: src/features/payments/generateSchedule.test.ts
 */
import { test, expect, type Page } from '@playwright/test'

const INSTRUMENT = {
  id: 1,
  name: 'GURMINA.USD.2024.01',
  platform: 'Fainex',
  currency: 'USD',
  couponRate: 11,
  startDate: '2024-12-30',
  endDate: '2026-12-14',
  paymentFrequency: 'monthly',
  paymentDayFrom: 15,
  paymentDayTo: 18,
  status: 'active',
  createdAt: '2024-12-30T00:00:00.000Z',
  updatedAt: '2024-12-30T00:00:00.000Z',
}

// 502 tokens × 20 USD = 10 040 USD
const PURCHASE_LOT = {
  id: 1,
  instrumentId: 1,
  purchaseDate: '2024-12-30',
  quantity: 502,
  pricePerToken: 20,
  totalCost: 10040,
  createdAt: '2024-12-30T00:00:00.000Z',
}

// Subset of the schedule generated by the fixed algorithm (principal = 10 040 USD)
// These match the "real payments" from the test suite.
const PAYMENT_RECORDS = [
  // period 0: Dec 30–31, 2024 (2 days / 366) → 6.03
  {
    id: 1,
    instrumentId: 1,
    periodIndex: 0,
    type: 'coupon',
    paymentDateFrom: '2025-01-15',
    paymentDateTo: '2025-01-18',
    expectedAmount: 6.03,
    status: 'scheduled',
  },
  // period 14: Feb 2026 (28 days / 365) → 84.72
  {
    id: 15,
    instrumentId: 1,
    periodIndex: 14,
    type: 'coupon',
    paymentDateFrom: '2026-03-15',
    paymentDateTo: '2026-03-18',
    expectedAmount: 84.72,
    status: 'scheduled',
  },
  // period 15: Mar 2026 (31 days / 365) → 93.80
  {
    id: 16,
    instrumentId: 1,
    periodIndex: 15,
    type: 'coupon',
    paymentDateFrom: '2026-04-15',
    paymentDateTo: '2026-04-18',
    expectedAmount: 93.8,
    status: 'scheduled',
  },
  // period 16: Apr 2026 (30 days / 365) → 90.77
  {
    id: 17,
    instrumentId: 1,
    periodIndex: 16,
    type: 'coupon',
    paymentDateFrom: '2026-05-15',
    paymentDateTo: '2026-05-18',
    expectedAmount: 90.77,
    status: 'scheduled',
  },
]

async function seedDB(page: Page) {
  await page.evaluate(
    async ({ instrument, lot, payments }) => {
      const db = await new Promise<IDBDatabase>((resolve, reject) => {
        const req = indexedDB.open('TokensTrackerDB')
        req.onsuccess = () => resolve(req.result)
        req.onerror = () => reject(req.error)
      })

      const clearStore = (name: string) =>
        new Promise<void>((res, rej) => {
          const tx = db.transaction(name, 'readwrite')
          tx.objectStore(name).clear().onsuccess = () => res()
          tx.onerror = () => rej(tx.error)
        })

      const putRecord = (name: string, record: object) =>
        new Promise<void>((res, rej) => {
          const tx = db.transaction(name, 'readwrite')
          tx.objectStore(name).put(record).onsuccess = () => res()
          tx.onerror = () => rej(tx.error)
        })

      await clearStore('instruments')
      await clearStore('purchaseLots')
      await clearStore('paymentRecords')

      await putRecord('instruments', instrument)
      await putRecord('purchaseLots', lot)
      for (const p of payments) await putRecord('paymentRecords', p)
    },
    { instrument: INSTRUMENT, lot: PURCHASE_LOT, payments: PAYMENT_RECORDS },
  )
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await page.waitForLoadState('networkidle')
  await seedDB(page)
  await page.goto('/instruments/1')
  await page.waitForLoadState('networkidle')
  await page.waitForTimeout(800)
})

test('payment schedule tab shows 2026 amounts (84.72, 93.80, 90.77)', async ({ page }) => {
  const pageText = await page.locator('body').innerText()
  expect(pageText).toContain('84,72') // currency formatter uses comma in ru locale
  expect(pageText).toContain('93,80')
  expect(pageText).toContain('90,77')
})

test('payment dates show correct month after accrual period', async ({ page }) => {
  const pageText = await page.locator('body').innerText()
  // February 2026 accrual → paid 15.03.2026
  expect(pageText).toContain('15.03.2026')
  // March 2026 accrual → paid 15.04.2026
  expect(pageText).toContain('15.04.2026')
  // April 2026 accrual → paid 15.05.2026
  expect(pageText).toContain('15.05.2026')
})

test('purchase lot shows correct token count and price', async ({ page }) => {
  const pageText = await page.locator('body').innerText()
  // 502 tokens at 20 USD each — check token count
  expect(pageText).toContain('502')
  // Price per token
  expect(pageText).toMatch(/20[,.]00/)
})
